Broad share spec
IGVF/seqspec pull request #2
Opened 2023-02-02 15:02 UTC by emattei

SHARE-seq seqspec file for the fastqs that will be submitted by Broad.

2023-02-14 20:01 UTC, sbooeshaghi requested changes
Thank you for taking the time submit a `seqspec` for the `SHARE-Seq` assay! I've added comments for my review. The `spec` has a good structure and a bit more work can make it entirely descriptive of the libraries generated with the SHARE-Seq assay.

The biggest point that needs addressing is the barcode structure. The `ATAC` region didn't contain any information about the `cell_barcodes`. This can be fixed by adding `Regions` in the `ATAC` modality that describe the barcode structure. Additionally, the barcode structure in the `RNA` modality appears to be missing important information about the combinatorial barcoding scheme that generates the final `cell_barcode`. This can be fixed by adding sub-`Regions` in the `cell_barcode` `Region`.

2023-02-15 21:10 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +    - region_id: ATAC
For `ATAC` fastq1 and fast2 only contain gDNA. The cell barcode is in the read name. That's why I asked in the IGVF slack if there was a way to describe that.

2023-02-15 21:10 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +doi: 10.1016/j.cell.2020.09.056
Sure, I will change this.

2023-02-15 21:15 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +          sequence_type: random
Can I just remove it and put it all in the parent `Region`?

2023-02-15 21:16 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +          sequence_type: random
I guess same thing here.  It seems that I don't have to have sub-`Regions`

2023-02-15 21:16 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +    - region_id: ATAC
Oops sorry I missed that. Will fix

2023-02-15 21:17 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +          sequence_type: random
As before.

2023-02-15 21:19 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +              region_id: cell_barcode
We are not going to submit data straight out of the sequencer. What you can see in the synapse is the exact format that we will submit to IGVF and what I am trying to describe in this YAML.

2023-02-15 21:19 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +              region_id: cell_barcode
Same as before.

2023-02-15 21:20 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +                filename: "gs://broad-buenrostro-bcl-outputs/192_PLATE1_PLATE2_whitelist.txt"
Sounds good.

2023-02-15 21:22 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +          region_id: R1.fastq.gz
Will fix.

2023-02-15 21:22 UTC, emattei commented on assays/SHARE-seq/broad_share_spec.yaml
> +          region_id: R2.fastq.gz
As above.

2023-02-16 17:12 UTC, emattei commented
* Added the barcode list
* Fixed doi url
* `region_id` is now unique
* Fixed `region_type` is now unique
* `!Region` now present
*  Fixed `sequence_type`
*  Changed barcode definitions

2023-07-06 19:33 UTC, sbooeshaghi commented
Hi Eugenio, thank you for making these changes. Could you please install the most recent version of seqspec and run `seqspec check` to verify the correctness and completeness of the spec? In addition, please supply FASTQ files (with 1 million reads) associated with the regions identified in the spec, in your PR. For more information please see the contributing page for more details (https://github.com/IGVF/seqspec/blob/main/docs/CONTRIBUTING.md). Thank you!

2023-08-16 19:00 UTC, sbooeshaghi commented
Hey Eugenio- just checking in. I'd like to get your spec merged into the repo!

2023-09-08 16:14 UTC, emattei commented
Hi Sina,
Since seqspec is going to be released per file I cannot provide a general version to put here anymore. What you have on the github is already enough as "general" seqspec for SHARE-seq. All the seqspecs relative to the files for IGVF will be in the portal. I guess we can close this pull request.

2023-09-08 16:14 UTC, closed without merging